name: pull-request
on:
  pull_request:
    types: [opened, synchronize, reopened]
  merge_group:

jobs:
  code:
    uses: justland/.github/.github/workflows/pnpm-verify.yml@main
    permissions:
      contents: read
    with:
      os: '["ubuntu-latest"]'
