name: release
on:
  push:
    branches: [main]

jobs:
  code:
    uses: justland/.github/.github/workflows/pnpm-verify.yml@main
    permissions:
      contents: read
    with:
      os: '["ubuntu-latest"]'
